name: Download

description: Download files from URL

inputs:
  accept:
    description: "Download files matching pattern"
    required: true
  output-path:
    description: "Path download files into"
    required: true
  url:
    descriotion: "URL to download files from"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download
      shell: sh
      run: |
        mkdir -p "${{ inputs.output-path }}"
        cd "${{ inputs.output-path }}"
        wget --no-verbose -e robots=off -c -r -l 1 \
            -A "${{ inputs.accept }}" "${{ inputs.url }}"
