// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Record {
    #[prost(int32, tag = "1")]
    pub data_type: i32,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<Payload>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Payload {
    #[prost(map = "string, string", tag = "1")]
    pub fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Task {
    #[prost(int32, tag = "1")]
    pub data_type: i32,
    #[prost(string, tag = "2")]
    pub object_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub data: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
}
/// Task command types sent from the server to a plugin.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaskCmd {
    TaskShutdown = 0,
    TaskUpdate = 1,
    TaskSetenv = 2,
    TaskRestart = 3,
}
impl TaskCmd {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TaskShutdown => "TASK_SHUTDOWN",
            Self::TaskUpdate => "TASK_UPDATE",
            Self::TaskSetenv => "TASK_SETENV",
            Self::TaskRestart => "TASK_RESTART",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TASK_SHUTDOWN" => Some(Self::TaskShutdown),
            "TASK_UPDATE" => Some(Self::TaskUpdate),
            "TASK_SETENV" => Some(Self::TaskSetenv),
            "TASK_RESTART" => Some(Self::TaskRestart),
            _ => None,
        }
    }
}
