// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Record {
    #[prost(int32, tag = "1")]
    pub data_type: i32,
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<Payload>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Payload {
    #[prost(map = "string, string", tag = "1")]
    pub fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Task {
    #[prost(int32, tag = "1")]
    pub data_type: i32,
    #[prost(string, tag = "2")]
    pub object_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub data: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub token: ::prost::alloc::string::String,
}
/// Task command types sent from the server to a plugin.
/// Generated from `TaskCmd` enum in transfer.proto.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaskCmd {
    TaskShutdown = 0,
    TaskUpdate   = 1,
    TaskSetenv   = 2,
    TaskRestart  = 3,
}
impl TaskCmd {
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TaskCmd::TaskShutdown => "TASK_SHUTDOWN",
            TaskCmd::TaskUpdate   => "TASK_UPDATE",
            TaskCmd::TaskSetenv   => "TASK_SETENV",
            TaskCmd::TaskRestart  => "TASK_RESTART",
        }
    }
}
