package userspace

const (
	TRACEPOINT_SYSCALLS_EXECVE   = 1
	TRACEPOINT_SYSCALLS_EXECVEAT = 2
	KPROBE_DO_EXIT               = 3
	KPROBE_EXIT_GROUP            = 4
	KRPOBE_SECURITY_BPRM_CHECK   = 5
	TRACEPOINT_SYSCALLS_PRCTL    = 6
	TRACEPOINT_SYSCALLS_PTRACE   = 7
)
