// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RawData struct {
	Data                 []*Record `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	Item                 []*Item   `protobuf:"bytes,2,rep,name=Item,proto3" json:"Item,omitempty"`
	AgentID              string    `protobuf:"bytes,3,opt,name=AgentID,proto3" json:"AgentID,omitempty"`
	IntranetIPv4         []string  `protobuf:"bytes,4,rep,name=IntranetIPv4,proto3" json:"IntranetIPv4,omitempty"`
	ExtranetIPv4         []string  `protobuf:"bytes,5,rep,name=ExtranetIPv4,proto3" json:"ExtranetIPv4,omitempty"`
	IntranetIPv6         []string  `protobuf:"bytes,6,rep,name=IntranetIPv6,proto3" json:"IntranetIPv6,omitempty"`
	ExtranetIPv6         []string  `protobuf:"bytes,7,rep,name=ExtranetIPv6,proto3" json:"ExtranetIPv6,omitempty"`
	Hostname             string    `protobuf:"bytes,8,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Version              string    `protobuf:"bytes,9,opt,name=Version,proto3" json:"Version,omitempty"`
	Product              string    `protobuf:"bytes,10,opt,name=Product,proto3" json:"Product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RawData) Reset()         { *m = RawData{} }
func (m *RawData) String() string { return proto.CompactTextString(m) }
func (*RawData) ProtoMessage()    {}
func (*RawData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *RawData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawData.Unmarshal(m, b)
}
func (m *RawData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawData.Marshal(b, m, deterministic)
}
func (m *RawData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawData.Merge(m, src)
}
func (m *RawData) XXX_Size() int {
	return xxx_messageInfo_RawData.Size(m)
}
func (m *RawData) XXX_DiscardUnknown() {
	xxx_messageInfo_RawData.DiscardUnknown(m)
}

var xxx_messageInfo_RawData proto.InternalMessageInfo

func (m *RawData) GetData() []*Record {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RawData) GetItem() []*Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *RawData) GetAgentID() string {
	if m != nil {
		return m.AgentID
	}
	return ""
}

func (m *RawData) GetIntranetIPv4() []string {
	if m != nil {
		return m.IntranetIPv4
	}
	return nil
}

func (m *RawData) GetExtranetIPv4() []string {
	if m != nil {
		return m.ExtranetIPv4
	}
	return nil
}

func (m *RawData) GetIntranetIPv6() []string {
	if m != nil {
		return m.IntranetIPv6
	}
	return nil
}

func (m *RawData) GetExtranetIPv6() []string {
	if m != nil {
		return m.ExtranetIPv6
	}
	return nil
}

func (m *RawData) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *RawData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RawData) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

type Record struct {
	DataType             int32    `protobuf:"varint,1,opt,name=DataType,proto3" json:"DataType,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Body                 *Item    `protobuf:"bytes,3,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetBody() *Item {
	if m != nil {
		return m.Body
	}
	return nil
}

type Item struct {
	Fields               map[string]string `protobuf:"bytes,1,rep,name=Fields,proto3" json:"Fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetFields() map[string]string {
	if m != nil {
		return m.Fields
	}
	return nil
}

//server --> agent
type Command struct {
	AgentCtrl            int32         `protobuf:"varint,1,opt,name=AgentCtrl,proto3" json:"AgentCtrl,omitempty"`
	Task                 *PluginTask   `protobuf:"bytes,2,opt,name=Task,proto3" json:"Task,omitempty"`
	Config               []*ConfigItem `protobuf:"bytes,3,rep,name=Config,proto3" json:"Config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetAgentCtrl() int32 {
	if m != nil {
		return m.AgentCtrl
	}
	return 0
}

func (m *Command) GetTask() *PluginTask {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *Command) GetConfig() []*ConfigItem {
	if m != nil {
		return m.Config
	}
	return nil
}

type PluginTask struct {
	//DataType which used to uniquely identify different  format of Data
	DataType int32 `protobuf:"varint,1,opt,name=DataType,proto3" json:"DataType,omitempty"`
	// Plugin name, which used to uniquely identify different plugins
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// Data transparently transmitted to the plugin
	Data string `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	// The token is used for reconciliation
	Token                string   `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginTask) Reset()         { *m = PluginTask{} }
func (m *PluginTask) String() string { return proto.CompactTextString(m) }
func (*PluginTask) ProtoMessage()    {}
func (*PluginTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{4}
}

func (m *PluginTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginTask.Unmarshal(m, b)
}
func (m *PluginTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginTask.Marshal(b, m, deterministic)
}
func (m *PluginTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginTask.Merge(m, src)
}
func (m *PluginTask) XXX_Size() int {
	return xxx_messageInfo_PluginTask.Size(m)
}
func (m *PluginTask) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginTask.DiscardUnknown(m)
}

var xxx_messageInfo_PluginTask proto.InternalMessageInfo

func (m *PluginTask) GetDataType() int32 {
	if m != nil {
		return m.DataType
	}
	return 0
}

func (m *PluginTask) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginTask) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *PluginTask) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConfigItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
	SHA256               string   `protobuf:"bytes,4,opt,name=SHA256,proto3" json:"SHA256,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=Signature,proto3" json:"Signature,omitempty"`
	DownloadURL          []string `protobuf:"bytes,6,rep,name=DownloadURL,proto3" json:"DownloadURL,omitempty"`
	Detail               string   `protobuf:"bytes,7,opt,name=Detail,proto3" json:"Detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigItem) Reset()         { *m = ConfigItem{} }
func (m *ConfigItem) String() string { return proto.CompactTextString(m) }
func (*ConfigItem) ProtoMessage()    {}
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{5}
}

func (m *ConfigItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigItem.Unmarshal(m, b)
}
func (m *ConfigItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigItem.Marshal(b, m, deterministic)
}
func (m *ConfigItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigItem.Merge(m, src)
}
func (m *ConfigItem) XXX_Size() int {
	return xxx_messageInfo_ConfigItem.Size(m)
}
func (m *ConfigItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigItem.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigItem proto.InternalMessageInfo

func (m *ConfigItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ConfigItem) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ConfigItem) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ConfigItem) GetSHA256() string {
	if m != nil {
		return m.SHA256
	}
	return ""
}

func (m *ConfigItem) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ConfigItem) GetDownloadURL() []string {
	if m != nil {
		return m.DownloadURL
	}
	return nil
}

func (m *ConfigItem) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*RawData)(nil), "grpc.RawData")
	proto.RegisterType((*Record)(nil), "grpc.Record")
	proto.RegisterType((*Item)(nil), "grpc.Item")
	proto.RegisterMapType((map[string]string)(nil), "grpc.Item.FieldsEntry")
	proto.RegisterType((*Command)(nil), "grpc.Command")
	proto.RegisterType((*PluginTask)(nil), "grpc.PluginTask")
	proto.RegisterType((*ConfigItem)(nil), "grpc.ConfigItem")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xad, 0xac, 0x2f, 0x6b, 0x9c, 0x40, 0x58, 0x42, 0x58, 0x4c, 0x29, 0x42, 0xf4, 0xa0, 0x93,
	0x29, 0x6e, 0x6b, 0xda, 0xdc, 0x12, 0x3b, 0x25, 0x86, 0x52, 0xcc, 0xc6, 0xed, 0xa1, 0xb7, 0x8d,
	0xb5, 0x36, 0xc2, 0xd2, 0xae, 0x2b, 0xad, 0xe3, 0xfa, 0xcf, 0xf5, 0xd6, 0xff, 0x55, 0xf6, 0x23,
	0x96, 0xec, 0x40, 0x4f, 0xda, 0x79, 0xf3, 0xfc, 0x66, 0xe6, 0xed, 0xac, 0x01, 0x56, 0xd5, 0x66,
	0x31, 0xd8, 0x54, 0x42, 0x0a, 0xe4, 0xa9, 0x73, 0xf2, 0xb7, 0x03, 0x21, 0xa1, 0xbb, 0x09, 0x95,
	0x14, 0xc5, 0xe0, 0xa9, 0x2f, 0x76, 0x62, 0x37, 0xed, 0x0d, 0xcf, 0x06, 0x9a, 0x4c, 0xd8, 0x42,
	0x54, 0x19, 0xd1, 0x19, 0xf4, 0x06, 0xbc, 0xa9, 0x64, 0x25, 0xee, 0x68, 0x06, 0x18, 0x86, 0x42,
	0x88, 0xc6, 0x11, 0x86, 0xf0, 0x66, 0xc5, 0xb8, 0x9c, 0x4e, 0xb0, 0x1b, 0x3b, 0x69, 0x44, 0x9e,
	0x43, 0x94, 0xc0, 0xd9, 0x94, 0xcb, 0x8a, 0x72, 0x26, 0xa7, 0xb3, 0xa7, 0x0f, 0xd8, 0x8b, 0xdd,
	0x34, 0x22, 0x47, 0x98, 0xe2, 0xdc, 0xfd, 0x6e, 0x71, 0x7c, 0xc3, 0x69, 0x63, 0x27, 0x3a, 0x23,
	0x1c, 0xbc, 0xd0, 0x19, 0x9d, 0xe8, 0x8c, 0x70, 0xf8, 0x42, 0x67, 0x84, 0xfa, 0xd0, 0xbd, 0x17,
	0xb5, 0xe4, 0xb4, 0x64, 0xb8, 0xab, 0x5b, 0x3d, 0xc4, 0x6a, 0x8a, 0x1f, 0xac, 0xaa, 0x73, 0xc1,
	0x71, 0x64, 0xa6, 0xb0, 0xa1, 0xca, 0xcc, 0x2a, 0x91, 0x6d, 0x17, 0x12, 0x83, 0xc9, 0xd8, 0x30,
	0x79, 0x84, 0xc0, 0x38, 0xa5, 0x94, 0x95, 0x57, 0xf3, 0xfd, 0x86, 0x61, 0x27, 0x76, 0x52, 0x9f,
	0x1c, 0x62, 0xf4, 0x1a, 0xa2, 0x79, 0x5e, 0xb2, 0x5a, 0xd2, 0x72, 0x83, 0x3b, 0xb1, 0x93, 0xba,
	0xa4, 0x01, 0x94, 0xbb, 0xb7, 0x22, 0xdb, 0x6b, 0xeb, 0x4e, 0xdc, 0x55, 0x78, 0xf2, 0xcb, 0xb8,
	0x8f, 0x06, 0x10, 0x7c, 0xc9, 0x59, 0x91, 0xd5, 0xf6, 0xa6, 0xae, 0x1a, 0xe6, 0xc0, 0x24, 0xee,
	0xb8, 0xac, 0xf6, 0xc4, 0xb2, 0xfa, 0x9f, 0xa1, 0xd7, 0x82, 0xd1, 0x05, 0xb8, 0x6b, 0xb6, 0xd7,
	0xbd, 0x45, 0x44, 0x1d, 0xd1, 0x25, 0xf8, 0x4f, 0xb4, 0xd8, 0x32, 0xdd, 0x52, 0x44, 0x4c, 0x70,
	0xdd, 0xf9, 0xe4, 0x24, 0x3b, 0x08, 0xc7, 0xa2, 0x2c, 0x29, 0xcf, 0x54, 0xef, 0xfa, 0x32, 0xc7,
	0xb2, 0x2a, 0xec, 0x60, 0x0d, 0x80, 0xde, 0x82, 0x37, 0xa7, 0xf5, 0x5a, 0x2b, 0xf4, 0x86, 0x17,
	0xa6, 0xa3, 0x59, 0xb1, 0x5d, 0xe5, 0x5c, 0xe1, 0x44, 0x67, 0x51, 0x0a, 0xc1, 0x58, 0xf0, 0x65,
	0xbe, 0xc2, 0xae, 0xee, 0xdc, 0xf2, 0x0c, 0xa6, 0x27, 0xb5, 0xf9, 0x64, 0x09, 0xd0, 0xfc, 0xfa,
	0xbf, 0x9e, 0x22, 0xf0, 0xbe, 0xa9, 0x5b, 0x34, 0xbd, 0xeb, 0xb3, 0xc2, 0xf4, 0x26, 0x9b, 0x25,
	0x34, 0xbb, 0x7b, 0x09, 0xfe, 0x5c, 0xac, 0x19, 0xc7, 0x9e, 0x19, 0x52, 0x07, 0xc9, 0x1f, 0x07,
	0xa0, 0x29, 0x7f, 0x10, 0x73, 0x8e, 0xc5, 0x74, 0x61, 0x5b, 0x40, 0x17, 0x6d, 0xad, 0x88, 0x7b,
	0xbc, 0x22, 0x57, 0x10, 0x3c, 0xdc, 0xdf, 0x0c, 0x3f, 0x8e, 0x6c, 0x1d, 0x1b, 0x29, 0xfb, 0x1e,
	0xf2, 0x15, 0xa7, 0x72, 0x5b, 0x31, 0xec, 0xeb, 0x54, 0x03, 0xa0, 0x18, 0x7a, 0x13, 0xb1, 0xe3,
	0x85, 0xa0, 0xd9, 0x77, 0xf2, 0xd5, 0x6e, 0x75, 0x1b, 0x52, 0xba, 0x13, 0x26, 0x69, 0x5e, 0xe0,
	0xd0, 0xe8, 0x9a, 0x68, 0x78, 0x0d, 0xdd, 0x79, 0x45, 0x79, 0xbd, 0x64, 0x15, 0x1a, 0xb4, 0xce,
	0xe7, 0xf6, 0xf9, 0x9a, 0xb7, 0xdd, 0x3f, 0x7f, 0x76, 0x5a, 0x5f, 0x66, 0xf2, 0x2a, 0x75, 0xde,
	0x39, 0xb7, 0xe1, 0x4f, 0x5f, 0xff, 0x17, 0x3c, 0x06, 0xfa, 0xf3, 0xfe, 0x5f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xba, 0xbc, 0xcc, 0xd8, 0x20, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransferClient is the client API for Transfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransferClient interface {
	Transfer(ctx context.Context, opts ...grpc.CallOption) (Transfer_TransferClient, error)
}

type transferClient struct {
	cc *grpc.ClientConn
}

func NewTransferClient(cc *grpc.ClientConn) TransferClient {
	return &transferClient{cc}
}

func (c *transferClient) Transfer(ctx context.Context, opts ...grpc.CallOption) (Transfer_TransferClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Transfer_serviceDesc.Streams[0], "/grpc.Transfer/Transfer", opts...)
	if err != nil {
		return nil, err
	}
	x := &transferTransferClient{stream}
	return x, nil
}

type Transfer_TransferClient interface {
	Send(*RawData) error
	Recv() (*Command, error)
	grpc.ClientStream
}

type transferTransferClient struct {
	grpc.ClientStream
}

func (x *transferTransferClient) Send(m *RawData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *transferTransferClient) Recv() (*Command, error) {
	m := new(Command)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TransferServer is the server API for Transfer service.
type TransferServer interface {
	Transfer(Transfer_TransferServer) error
}

// UnimplementedTransferServer can be embedded to have forward compatible implementations.
type UnimplementedTransferServer struct {
}

func (*UnimplementedTransferServer) Transfer(srv Transfer_TransferServer) error {
	return status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}

func RegisterTransferServer(s *grpc.Server, srv TransferServer) {
	s.RegisterService(&_Transfer_serviceDesc, srv)
}

func _Transfer_Transfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransferServer).Transfer(&transferTransferServer{stream})
}

type Transfer_TransferServer interface {
	Send(*Command) error
	Recv() (*RawData, error)
	grpc.ServerStream
}

type transferTransferServer struct {
	grpc.ServerStream
}

func (x *transferTransferServer) Send(m *Command) error {
	return x.ServerStream.SendMsg(m)
}

func (x *transferTransferServer) Recv() (*RawData, error) {
	m := new(RawData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Transfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Transfer",
	HandlerType: (*TransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transfer",
			Handler:       _Transfer_Transfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
