# non-core build
name: non-CO-RE-daily
on:
  schedule:
    - cron: "0 0 * * *"

env:
  GO_VERSION: "1.18"

jobs:
  non-CO-RE-ubuntu-latest:
    name: "Build eBPF driver(header)"
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
    steps:
      - name: "Git checkout"
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: "Install Dependencies"
        uses: ./.github/actions/build-dependencies
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Download Kernel Headers"
        run: |
          sudo apt-get install build-essential
          sudo apt-get update
          sudo apt-get install linux-headers-$(uname -r)
      - name: Build non-CO-RE
        run: |
          cd plugins/ebpfdriver
          make
