# non-core build
name: non-CO-RE-daily
on:

env:
  DOWNLOAD: ".download"
  UNPACKED: ".unpacked"

env:
  GO_VERSION: "1.17"

jobs:
  non-CO-RE:
    name: "Build eBPF driver(header)"
    runs-on: ubuntu-${{ matrix.release.name }}
    timeout-minutes: 90
    env:
      MIRROR: "https://mirrors.edge.kernel.org/ubuntu"
      FLAVOUR: generic
    strategy:
      matrix:
        kernel:
          [
            { "name": "20.04", "kernel": "5.4.0" },
            { "name": "18.04", "kernel": "4.19.0" },
          ]
    steps:
      - name: "Git checkout"
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: "Install Dependencies"
        uses: ./.github/actions/build-dependencies
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: ""

      - name: Build non-CO-RE
        run: |
          cd plugin/driver/eBPF
          make debug
