name: Hades-driver

on:
  push:
    tags:
    - edriver-v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry & build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            plugins/edriver/target
          key: ${{ runner.os }}-release-edriver-${{ hashFiles('plugins/edriver/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-release-edriver-

      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends build-essential pkgconf libelf-dev llvm-14 clang-14
          for tool in clang llc llvm-strip
          do
            sudo rm -f /usr/bin/$tool
            sudo ln -s /usr/bin/${tool}-14 /usr/bin/$tool
          done

      - name: Build
        run: |
          cd plugins/edriver
          make build
          cd ../..

      - name: Strip & checksum
        run: |
          strip plugins/edriver/edriver
          sha256sum plugins/edriver/edriver > plugins/edriver/checksum.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: edriver
          path: |
            plugins/edriver/edriver
            plugins/edriver/checksum.txt
          retention-days: 7
      
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Extract version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: edriver
        path: /tmp/edriver

    - name: Package
      working-directory: /tmp/edriver
      run: |
        tar zcvf /tmp/${{ env.RELEASE_VERSION }}.tgz edriver checksum.txt

    - name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        prerelease: false
        name: Release ${{ github.ref_name }}
        files: /tmp/${{ env.RELEASE_VERSION }}.tgz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    needs:
    - build
